controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
accueil:
    path: /
    controller: App\Controller\ProduitController::index
        
produits:
    path: /produits
    controller: App\Controller\ProduitController::index
    
produits_index:
    path: /produits
    controller: App\Controller\ProduitController::index

produit_new:
    path: /produits/new
    controller: App\Controller\ProduitController::new

produit_edit:
    path: /produits/edit/{id}
    controller: 'App\Controller\ProduitController::edit'
    methods: ['GET', 'POST']

produit_delete:
    path: /produits/delete/{id}
    controller: 'App\Controller\ProduitController::delete'
    methods: ['POST']

produit_show:
    path: /produits/show/{id}
    controller: 'App\Controller\ProduitController::show'

produits_par_categorie:
    path: '/produits/{categorie}'
    controller: 'App\Controller\ProduitController::produitsParCategorie'
