controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
accueil:
    path: /
    controller: App\Controller\HomeController::index
        
produits:
    path: /produits
    controller: App\Controller\ProduitController::index