<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFp9w2Zw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFp9w2Zw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFp9w2Zw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFp9w2Zw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFp9w2Zw\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fp9w2Zw',
    'container.build_id' => 'c6ec6180',
    'container.build_time' => 1712754993,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFp9w2Zw');
